### PR TITLE
Feature/adpcm fixes

### PR DESCRIPTION
**Pull request by jacmet**
The ADPCM source code and description contained a number of errors, fix that. I did not update the SVG, but it doesn't seem to use the exact sample values anyway.

### CODE REVIEW

**Comment by fabiensanglard** [comment]
Are you sure about the line

`stepSizeIndex += transitionTable[nibble & 0x7];`

It should be multiplied by the stepSize shouldn't it?

**Comment by jacmet** [comment]
> Are you sure about the line
> 
> `stepSizeIndex += transitionTable[nibble & 0x7];`
> 
> It should be multiplied by the stepSize shouldn't it?

No, the transitionTable only has 8 elements (0..7) and it also matches the description from Dialogic: https://multimedia.cx/mirror/dialogic-adpcm.pdf
Ideally the code would do some range checking, but I left it out for clarity.

**Comment by fabiensanglard** [comment]
Thank you so much for your help :) !

**Comment by jacmet** [comment]
> Thank you so much for your help :) !

And thank you! I really enjoy your writings!

**Pull request merged**
